# Generated by Django 4.0.3 on 2022-04-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('Code_date', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code_dep', models.IntegerField(primary_key=True, serialize=False)),
                ('A_dep', models.CharField(default='DEP', max_length=25)),
                ('Lib_dep', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Fonctionnaire',
            fields=[
                ('code_F', models.IntegerField(primary_key=True, serialize=False)),
                ('cin_F', models.CharField(max_length=255)),
                ('nom_F', models.CharField(max_length=255)),
                ('prenom_F', models.CharField(max_length=255)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('Code_prest', models.IntegerField(primary_key=True, serialize=False)),
                ('Lib_prest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code_service', models.IntegerField(primary_key=True, serialize=False)),
                ('Lib_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vis_type',
            fields=[
                ('Id_type', models.IntegerField(primary_key=True, serialize=False)),
                ('Lib_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('code_visiteur', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_visiteur', models.CharField(max_length=255)),
                ('prenom_visiteur', models.CharField(max_length=255)),
                ('CIN', models.CharField(max_length=25)),
                ('Tel', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=255)),
                ('Entreprise', models.CharField(max_length=255)),
                ('sexe', models.CharField(default='F', max_length=15)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.vis_type')),
            ],
        ),
        migrations.CreateModel(
            name='Histo_Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_F', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.fonctionnaire')),
                ('code_Pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.prestation')),
                ('code_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.date')),
                ('code_vist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.visiteur')),
            ],
        ),
        migrations.AddField(
            model_name='fonctionnaire',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_visits.service'),
        ),
    ]
