# Generated by Django 4.0.3 on 2022-04-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='time',
        ),
        migrations.AddField(
            model_name='date',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
