# Generated by Django 4.0.3 on 2022-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_visits', '0003_alter_date_visit_date_alter_date_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='visit_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='visit_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
