# Generated by Django 4.0.3 on 2022-04-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_visits', '0004_alter_date_visit_date_alter_date_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='histo_prestation',
            name='status',
            field=models.CharField(choices=[('en_coure', 'En coure'), ('traité', 'traité'), ('attente', 'en attente')], default='en_coure', max_length=55),
        ),
    ]
